### PR TITLE
Cloud Subnet Sizing

### LINKED ISSUE #5: How about an "exclude aws reserved IPs" checkbox?
Might be useful.

### PR DESCRIPTION
**Pull request by byroncollins**
Cloud subnet sizing functionality based on feedback from original [PR](https://github.com/ckabalan/visualsubnetcalc/pull/8) 

Enable AWS and Azure modes for calculating Usable IPs and enforcing smallest subnet size based on Azure and AWS restrictions.

Standard mode (Default)
- Smallest subnet: /32
AWS mode  
 - Smallest subnet: /29
Azure mode  
 - Smallest subnet: /28

- Mode selection available under the Tools menu
- Mode can be modified after designed - validation is done on smallest subnet sizing allowed for selected mode and rolled back to previous Mode if validation fails.

closes #5

### CODE REVIEW

**Comment by byroncollins** [comment]
Hi @ckabalan 

I got busy just after submitting the original PR but I had some time this week so knocked out a new PR based on the feedback from the original PR that I submitted.

**Comment by ckabalan** [comment]
@byroncollins Appreciate the enthusiasm for this project, I too got busy and will commit to giving you feedback tomorrow and I really hope to merge this week. I started my own work from the `develop` branch so will see where we intersect. Thanks again!

**Comment by byroncollins** [comment]
> @byroncollins Appreciate the enthusiasm for this project, I too got busy and will commit to giving you feedback tomorrow and I really hope to merge this week. I started my own work from the `develop` branch so will see where we intersect. Thanks again!

 Looking forward to seeing where we both ended up!

**Comment by ckabalan** [comment]
Like last time will keep communicating here...

**Comment by ckabalan** [comment]
This is live on the website. Docker builds are broken for some reason. I'll have to take a look at that tomorrow, but we're up!

Thanks for your contributions @byroncollins . I am really impressed at the effort you took to account for edge cases like importing inconsistent configs, or switching after smaller subnets existed. Made my job a lot easier, and I really tried to break it but your core functionality is unchanged. I can't get it to accept (via import or URL) or click to get an invalid configuration. I just changes how the errors are displayed.

I still have to review your other one(s).

Here are my notes for the changes I made to your code before merging to main. They're also in the commits above.

```
* Want to keep Meta Description short for SEO purposes.
* Elected to use built-in Bootstrap mode highlighting versus changing
  the text style
* Removed the Usable IPs popovers in favor of tooltips + hyperlink
* No need to increase the config version. That is only for breaking
  changes. We can assume 'Standard' for all URLs that do not have a mode
  for backwards compatibility. Incrementing the config version is when
  we have a breaking change like changing existing key names or other
  edge cases we can't code around with high confidence.
* Changed the modals slightly to include more information and links to
  documentation.
  * Fixed validation pattern for IP addresses in jQuery Validation. It was
  missing escape characters for the periods so "192.168." was showing as
  a fully valid address.
* Changed the validation error display to be Bootstrap tooltips instead
  of additional elements that shift the contents of the page.
* Added custom tooltip style for validation errors.
* Updated jQuery Validation dependencies.
```

**Comment by byroncollins** [comment]
> This is live on the website. Docker builds are broken for some reason. I'll have to take a look at that tomorrow, but we're up!
> 
> Thanks for your contributions @byroncollins . I am really impressed at the effort you took to account for edge cases like importing inconsistent configs, or switching after smaller subnets existed. Made my job a lot easier, and I really tried to break it but your core functionality is unchanged. I can't get it to accept (via import or URL) or click to get an invalid configuration. I just changes how the errors are displayed.
> 
> I still have to review your other one(s).
> 
> Here are my notes for the changes I made to your code before merging to main. They're also in the commits above.
> 
> ```
> * Want to keep Meta Description short for SEO purposes.
> * Elected to use built-in Bootstrap mode highlighting versus changing
>   the text style
> * Removed the Usable IPs popovers in favor of tooltips + hyperlink
> * No need to increase the config version. That is only for breaking
>   changes. We can assume 'Standard' for all URLs that do not have a mode
>   for backwards compatibility. Incrementing the config version is when
>   we have a breaking change like changing existing key names or other
>   edge cases we can't code around with high confidence.
> * Changed the modals slightly to include more information and links to
>   documentation.
>   * Fixed validation pattern for IP addresses in jQuery Validation. It was
>   missing escape characters for the periods so "192.168." was showing as
>   a fully valid address.
> * Changed the validation error display to be Bootstrap tooltips instead
>   of additional elements that shift the contents of the page.
> * Added custom tooltip style for validation errors.
> * Updated jQuery Validation dependencies.
> ```



> This is live on the website. Docker builds are broken for some reason. I'll have to take a look at that tomorrow, but we're up!
> 
> Thanks for your contributions @byroncollins . I am really impressed at the effort you took to account for edge cases like importing inconsistent configs, or switching after smaller subnets existed. Made my job a lot easier, and I really tried to break it but your core functionality is unchanged. I can't get it to accept (via import or URL) or click to get an invalid configuration. I just changes how the errors are displayed.
> 
> I still have to review your other one(s).
> 
> Here are my notes for the changes I made to your code before merging to main. They're also in the commits above.
> 
> ```
> * Want to keep Meta Description short for SEO purposes.
> * Elected to use built-in Bootstrap mode highlighting versus changing
>   the text style
> * Removed the Usable IPs popovers in favor of tooltips + hyperlink
> * No need to increase the config version. That is only for breaking
>   changes. We can assume 'Standard' for all URLs that do not have a mode
>   for backwards compatibility. Incrementing the config version is when
>   we have a breaking change like changing existing key names or other
>   edge cases we can't code around with high confidence.
> * Changed the modals slightly to include more information and links to
>   documentation.
>   * Fixed validation pattern for IP addresses in jQuery Validation. It was
>   missing escape characters for the periods so "192.168." was showing as
>   a fully valid address.
> * Changed the validation error display to be Bootstrap tooltips instead
>   of additional elements that shift the contents of the page.
> * Added custom tooltip style for validation errors.
> * Updated jQuery Validation dependencies.
> ```



Tool tips is a much better way to display the relevant Azure/AWS information.

re: Docker. That's my fault that docker builds have broke because I used sudo to install global module which I now know is not the recommended way and I should of used prefix. I'm happy to fix as I broke it!

**Pull request merged**
