### PR TITLE
Add support for /31 and /32 subnets

### PR DESCRIPTION
**Pull request by Supermathie**
/31 subnets are defined by RFC 3021 and are intended for point-to-point links;
they do not reserve an IP for the network number or the broadcast address.

/32 subnets are loopback IPs.

### CODE REVIEW

**Comment by Supermathie** [comment]
image

**Comment by ckabalan** [comment]
Initial glance is this looks REALLY good to me. Thanks for your contribution. I'll do some testing and merge as soon as possible.

Having not used /31 networks in practice, is it worth placing a note somewhere that these have a specific purpose? I've reviewed RFC3021 and my concern is someone splitting beyond /30 and intending to use a /31 in a NON-point-to-point scenario. Maybe an asterisk, or otherwise highlighting these subnets?

**Comment by Supermathie** [comment]
Maybe an asterisk under Usable IPs or Hosts?

(my CSS is not really good enough to prototype this :D)

> a NON-point-to-point scenario

There's no physical limitation on this, it's all software support - both ends need to be RFC3021 compliant.

So maybe a note indicating "RFC3021 (P-t-P) network" would work.

**Comment by Supermathie** [comment]
Or perhaps a checkbox to:
> Enable subnets smaller than /30 (/31 RFC 3021 Point-to-Point networks, and /32 single IPs)

**Comment by Supermathie** [comment]
oh bollocks @ckabalan an unintentional change snuck into f1970bde - I accidentally committed the absolute path change I had made to be able to test it locally

**Comment by ckabalan** [comment]
No problem, I went back and forth on this. Relative paths are the right choice here, during development I just didn't want to bother figuring out how to make WebStorm behave correctly. I switched to using the node webserver and forgot to go back it's all good.

This is live on the website with a few other small changes. v1.1.0 - 52e14b8

Thanks for your contribution! Any other feedback is absolutely welcome.

**Comment by ckabalan** [comment]
I also decided to forego a note about PtP/Loopback. I'll keep it in mind but I think it's an edge case that would affect the visual clarity/consistency. Leading thought was an asterisk with relevant mouseover text next to the network/host portion of the table.

**Pull request merged**
