### PR TITLE
Feature/cloud

### LINKED ISSUE #5: How about an "exclude aws reserved IPs" checkbox?
Might be useful.

### PR DESCRIPTION
**Pull request by byroncollins**
Added both an azure and aws mode. They basically reserve the same number of IPs in a subnet but AWS has a smaller subnet restriction of /27 vs Azure of /28.

You'd obviously  thought about this so I just built the functionality around what you had already started to develop.

To test the clipboard.writeText feature  I had to test with HTTPs so add documentation and commands for that.
 
 Closes #5

### CODE REVIEW

**Comment by ckabalan** [comment]
@byroncollins At first glance of the code this looks really good. I'll dive into this later this week as I'm starting a new job tomorrow (Monday). Expect it to be merged by the end of the week. PR is much appreciated.

**Comment by ckabalan** [comment]
Hi @byroncollins,

I like where this is going, and I have some feedback. First, do you want to make these adjustments, or do you want me to merge this PR into a feature branch and begin working there?

- I think we need to change how the selection works. I'm thinking maybe a subsection under the Tools menu with a divider? Looking at the design tenets we want to keep it simple for first time users, and this is more of an advanced feature, so I think should NOT be an always-visible UI element.
- Most people will choose the mode after they've already started splitting subnets, so we need to add some logic to re-calculate the values when the mode changes. We can block selecting the mode if any of the subnets are incompatible with the cloud provider (like a /30). I've been wanting to add a feature to support switching the top level network address and cascading that to all the split subnets, this could be related. For example moving 10.0.0.0/16 -> 10.33.0.0/16 but keeping all the splits/notes/colors the same.
- We should add a mouse-over popup to the Usable IPs header that indicates the mode and when moused-over explains the reserved addresses by cloud. For example "Usable IPs (AWS)" where AWS is a mouseover which would show the 5 reserved addresses in each network.

Thoughts? I'm happy to accept your changes as-is and build upon them, or have you do some revisions.

**Comment by byroncollins** [comment]
> Hi @byroncollins,
> 
> I like where this is going, and I have some feedback. First, do you want to make these adjustments, or do you want me to merge this PR into a feature branch and begin working there?
> 
>     * I think we need to change how the selection works. I'm thinking maybe a subsection under the Tools menu with a divider? Looking at the design tenets we want to keep it simple for first time users, and this is more of an advanced feature, so I think should NOT be an always-visible UI element.
> 
>     * Most people will choose the mode after they've already started splitting subnets, so we need to add some logic to re-calculate the values when the mode changes. We can block selecting the mode if any of the subnets are incompatible with the cloud provider (like a /30). I've been wanting to add a feature to support switching the top level network address and cascading that to all the split subnets, this could be related. For example moving 10.0.0.0/16 -> 10.33.0.0/16 but keeping all the splits/notes/colors the same.
> 
>     * We should add a mouse-over popup to the Usable IPs header that indicates the mode and when moused-over explains the reserved addresses by cloud. For example "Usable IPs (AWS)" where AWS is a mouseover which would show the 5 reserved addresses in each network.
> 
> 
> Thoughts? I'm happy to accept your changes as-is and build upon them, or have you do some revisions.

Hi @ckabalan 

I'm happy to take your steer on this and also your feedback around design.

It's fine by me If you want to merge this PR into a feature branch to continue to work,  whatever you think is best. I'm also happy to work on the adjustments together, as you have suggested.

Cheers
Byron

**Comment by ckabalan** [comment]
@byroncollins I'll merge it into a new feature branch and get to work. Will keep communicating here until we're live.

**Pull request merged**
